// app/(site)/layout.jsx
import { Navbar } from '@/components/layout/navbar';
import { Footer } from '@/components/layout/footer';

export const metadata = {
  title: 'Matrix Services pvt ltd',
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <>
      <Navbar />
       <main className="relative">
        {children}
      </main>
      <Footer />
    </>
  );
}
